name: Sync i18n files

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: [main]
    paths:
      - "src/lang/en/**"
  workflow_dispatch:

jobs:
  sync_i18n:
    name: Generate and i18n files
    runs-on: ubuntu-latest
    env:
      SYNC_PR_BRANCH: ${{ vars.SYNC_LANG_PR_BRANCH || 'chore/auto-update-i18n' }}
      SYNC_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: Checkout frontend codes
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout backend codes
        uses: actions/checkout@v7
        with:
          repository: ${{ vars.SYNC_LANG_ENV_BACKEND_REPOSITORY || 'OpenListTeam/OpenList' }}
          ref: guangyapan
          path: backend
          fetch-depth: 0
          submodules: recursive

      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"
          cache-dependency-path: backend/go.sum

      - name: Generate and update lang files
        run: |
          cd backend
          go run ./main.go lang --frontend-path ../
          cd ..

      - name: Check for changes and stage
        id: verify-changed-files
        run: |
          cp -f ./backend/lang/*.json ./src/lang/en/ 2>/dev/null || :
          if git diff --quiet HEAD -- src/lang/en/; then
            echo "No changes detected in src/lang/en/"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in src/lang/en/"
            git add src/lang/en/
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup CI Bot
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git commit -m "chore: auto update i18n file"
          # Skip pushing if triggered by a pull request
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            git push
          fi

      - name: Sync to Crowdin
        if: ${{ steps.verify-changed-files.outputs.changed == 'true' || github.event_name == 'push' }}
        uses: ./.github/actions/sync_to_crowdin
        with:
          crowdin_project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          crowdin_personal_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

permissions:
  contents: write
  pull-requests: write
